/**
 * Section 14 — UI State Machine
 * All 15 states and transition events from the blueprint.
 */

export type AppUIState =
  | "ONBOARDING"
  | "SESSION_PREVIEW"
  | "DELIVERY_AUDITORY_VISUAL"
  | "COMPREHENSION_GATE"
  | "ANALYTIC_BREAKDOWN"
  | "KINESTHETIC_WORDCARD"
  | "KINESTHETIC_CLASSIFICATION"
  | "ORAL_PREPARATION"
  | "ORAL_ACTIVE"
  | "STT_INPUT"
  | "FEEDBACK_DISPLAY"
  | "RECOVERY_BREAK"
  | "SESSION_DEBRIEF"
  | "SETTINGS"
  | "PROFILE_REVIEW";

export type UIEventType =
  | "ONBOARDING_COMPLETE"
  | "USER_CONFIRMS_READY"
  | "AUDIO_COMPLETE"
  | "USER_SELECTS_YES"
  | "USER_SELECTS_REPLAY"
  | "USER_SELECTS_EXPLAIN"
  | "BREAKDOWN_COMPLETE"
  | "TASK_COMPLETE"
  | "TASK_SKIPPED"
  | "COUNTDOWN_COMPLETE"
  | "USER_SELECTS_READY_EARLY"
  | "USER_SELECTS_TYPE_INSTEAD"
  | "SPEECH_DETECTED_AND_ENDED"
  | "TIMEOUT_NO_SPEECH"
  | "USER_ABANDONS"
  | "SUBMISSION_COMPLETE"
  | "USER_DISMISSES"
  | "SESSION_COMPLETE"
  | "BREAK_COMPLETE"
  | "USER_ENDS_SESSION"
  | "USER_EXITS"
  | "LOAD_ESCALATION";

export interface UIEvent {
  type: UIEventType;
  payload?: Record<string, unknown>;
}

export interface UIStateTransitionResult {
  from: AppUIState;
  to: AppUIState;
  event: UIEventType;
  valid: boolean;
  error?: string;
}

export const APP_UI_STATES: AppUIState[] = [
  "ONBOARDING",
  "SESSION_PREVIEW",
  "DELIVERY_AUDITORY_VISUAL",
  "COMPREHENSION_GATE",
  "ANALYTIC_BREAKDOWN",
  "KINESTHETIC_WORDCARD",
  "KINESTHETIC_CLASSIFICATION",
  "ORAL_PREPARATION",
  "ORAL_ACTIVE",
  "STT_INPUT",
  "FEEDBACK_DISPLAY",
  "RECOVERY_BREAK",
  "SESSION_DEBRIEF",
  "SETTINGS",
  "PROFILE_REVIEW",
];

export const UI_EVENT_TYPES: UIEventType[] = [
  "ONBOARDING_COMPLETE",
  "USER_CONFIRMS_READY",
  "AUDIO_COMPLETE",
  "USER_SELECTS_YES",
  "USER_SELECTS_REPLAY",
  "USER_SELECTS_EXPLAIN",
  "BREAKDOWN_COMPLETE",
  "TASK_COMPLETE",
  "TASK_SKIPPED",
  "COUNTDOWN_COMPLETE",
  "USER_SELECTS_READY_EARLY",
  "USER_SELECTS_TYPE_INSTEAD",
  "SPEECH_DETECTED_AND_ENDED",
  "TIMEOUT_NO_SPEECH",
  "USER_ABANDONS",
  "SUBMISSION_COMPLETE",
  "USER_DISMISSES",
  "SESSION_COMPLETE",
  "BREAK_COMPLETE",
  "USER_ENDS_SESSION",
  "USER_EXITS",
  "LOAD_ESCALATION",
];